import dayjs from "dayjs";

export const START_DATE = dayjs("2019-11-01");
export const END_DATE = dayjs("2023-10-01");

export enum Role {
  MARKETING = "MARKETING",
  SALES = "SALES",
  ADMIN = "ADMIN",
}

export enum Permission {
  SEGMENT_CUSTOMERS_BY_SPENDING = "SEGMENT CUSTOMERS BY SPENDING",
  FORMAT_NEWSLETTER_TEMPLATE = "FORMAT NEWSLETTER TEMPLATE",
  CREATE_AND_SEND_NEWSLETTER = "CREATE AND SEND NEWSLETTER",
  VIEW_SALES_METRICS = "VIEW SALES METRICS",
  ACCESS_AND_FILTER_PURCHASE_HISTORY = "ACCESS AND FILTER PURCHASE HISTORY",
  MANAGE_USER_ACCOUNTS = "MANAGE USER ACCOUNTS",
  EXPORT_FILTERED_DATA = "EXPORT FILTERED DATA",
}
